#!/bin/bash
# This is a simple build script and will be executed on your CI system if
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

#!/bin/bash

REDIS_VERSION=2.8.13
MAKE_IS_DONE="no"

if [ ! -d ${OPENSHIFT_DEPENDENCIES_DIR}/redis ]; then
  cd ${OPENSHIFT_TMP_DIR}
  if [ ! -d redis-${REDIS_VERSION} ]; then
    curl -L -o redis-${REDIS_VERSION}.tar.gz http://download.redis.io/releases/redis-${REDIS_VERSION}.tar.gz
    tar -xvzf redis-${REDIS_VERSION}.tar.gz
  fi
  cd redis-${REDIS_VERSION}
  echo "Start compiling Redis ${REDIS_VERSION} on OpenShift (i'll take a while)"
  PREFIX=${OPENSHIFT_DEPENDENCIES_DIR}redis make -e install

  mkdir -p ${OPENSHIFT_DATA_DIR}redis/data
  MAKE_IS_DONE="yes"
fi

if [ "$MAKE_IS_DONE" == "yes" ]; then
  echo "Make is done, now create the patch"
  cat <<EOF >${OPENSHIFT_TMP_DIR}redis.conf.patch
17c17
< daemonize no
---
> daemonize yes
21,21c21
< pidfile /var/run/redis.pid
---
> pidfile ${OPENSHIFT_DATA_DIR}redis/redis.pid
25c25
< port 6379
---
> port 0
36,37c36,37
< # unixsocket /tmp/redis.sock
< # unixsocketperm 755
---
> unixsocket ${OPENSHIFT_DATA_DIR}redis/redis.sock
> unixsocketperm 755
107c107
< dir ./
---
> dir ${OPENSHIFT_DATA_DIR}redis/data

EOF
  patch ${OPENSHIFT_TMP_DIR}redis-${REDIS_VERSION}/redis.conf ${OPENSHIFT_TMP_DIR}redis.conf.patch -o ${OPENSHIFT_DEPENDENCIES_DIR}redis/bin/redis.conf
fi

#cd ${OPENSHIFT_DEPENDENCIES_DIR}redis
[ -f ${OPENSHIFT_DATA_DIR}redis/redis.pid ] || ${OPENSHIFT_DEPENDENCIES_DIR}redis/bin/redis-server ${OPENSHIFT_DEPENDENCIES_DIR}redis/bin/redis.conf

